version: '3.8'

services:
  eyesee-storage:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z
    environment:
      MINIO_ROOT_USER: ADMIN
      MINIO_ROOT_PASSWORD: PASSWORD
      MINIO_BROWSER: off
    command: server /data --console-address ":9001"

  eyesee-service:
    build: .
    read_only: true
    ports:
      - "25910:25910"
    depends_on:
      - eyesee-storage
